/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.climaregist.view.graficos;

import javax.swing.JPanel;

/**
 *
 * @author tarci
 */
public class GraficosView extends javax.swing.JDialog {

    /**
     * Creates new form GraficosView
     */
    public GraficosView(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public JPanel getPanelGraficoPressao() {
        return panelGraficoPressao;
    }

    public JPanel getPanelGraficoTemperatura() {
        return panelGraficoTemperatura;
    }

    public JPanel getPanelGraficoUmidade() {
        return panelGraficoUmidade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanelGrafico = new javax.swing.JTabbedPane();
        panelGraficoTemperatura = new javax.swing.JPanel();
        panelGraficoUmidade = new javax.swing.JPanel();
        panelGraficoPressao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout panelGraficoTemperaturaLayout = new javax.swing.GroupLayout(panelGraficoTemperatura);
        panelGraficoTemperatura.setLayout(panelGraficoTemperaturaLayout);
        panelGraficoTemperaturaLayout.setHorizontalGroup(
            panelGraficoTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelGraficoTemperaturaLayout.setVerticalGroup(
            panelGraficoTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        tabbedPanelGrafico.addTab("Temperatura", panelGraficoTemperatura);

        javax.swing.GroupLayout panelGraficoUmidadeLayout = new javax.swing.GroupLayout(panelGraficoUmidade);
        panelGraficoUmidade.setLayout(panelGraficoUmidadeLayout);
        panelGraficoUmidadeLayout.setHorizontalGroup(
            panelGraficoUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelGraficoUmidadeLayout.setVerticalGroup(
            panelGraficoUmidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        tabbedPanelGrafico.addTab("Umidade", panelGraficoUmidade);

        javax.swing.GroupLayout panelGraficoPressaoLayout = new javax.swing.GroupLayout(panelGraficoPressao);
        panelGraficoPressao.setLayout(panelGraficoPressaoLayout);
        panelGraficoPressaoLayout.setHorizontalGroup(
            panelGraficoPressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelGraficoPressaoLayout.setVerticalGroup(
            panelGraficoPressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        tabbedPanelGrafico.addTab("Pressão", panelGraficoPressao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanelGrafico, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanelGrafico)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelGraficoPressao;
    private javax.swing.JPanel panelGraficoTemperatura;
    private javax.swing.JPanel panelGraficoUmidade;
    private javax.swing.JTabbedPane tabbedPanelGrafico;
    // End of variables declaration//GEN-END:variables
}
